name: mmoInfoFood
version: ${releaseVersion}.${buildNumber}
description: Adds a {food} token to the mmoInfo token list.
author: mmoMinecraftDev
website: http://mmo.me.uk
main: mmo.Info.mmoInfoFood
depend: [Spout,mmoCore,mmoInfo]
permissions:
  mmo.info.food:
    description: Allows {food} to show the current players hunger level
    default: true
